language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.12.3
script:
  - sbt coverage test coverageReport doc
after_script:
  - bash <(curl -s https://codecov.io/bash)
