language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk7
      scala: 2.11.7
script:
  - sbt coverage test doc
after_script:
  - bash <(curl -s https://codecov.io/bash)
